name: Publish to Github Package Registry
on:
  release:
    types: [published]

jobs:
  create_release_notes:
    runs-on: ubuntu-latest
    name: Publish Package to Github Package
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: Install Packages
        run: |
          npm ci
      - name: Build Package
        run: |
          cp --verbose ./src/environments/environment.example.ts ./src/environments/environment.prod.ts
          cp --verbose ./src/environments/environment.example.ts ./src/environments/environment.ts
          cp --verbose ./src/environments/environment.example.ts ./src/environments/environment.dev.ts
          npm run build
      - name: Prepare Package
        run: |
          npm run create-publish-package -- github-repository
          cp -rf ./publish-package.json package.json
      - name: Upload Package
        run: |
          ./deploy_github_package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}